SCOPE BEGIN
  Z =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  a =>
    CONST BEGIN
      type:
        INTEGER
      value:
        16807
    END CONST
  g =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  m =>
    CONST BEGIN
      type:
        INTEGER
      value:
        2147483647
    END CONST
  q =>
    CONST BEGIN
      type:
        INTEGER
      value:
        127773
    END CONST
  r =>
    CONST BEGIN
      type:
        INTEGER
      value:
        2836
    END CONST
END SCOPE
