SCOPE BEGIN
  a =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  a2 =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  b =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  c =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  d =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  e =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  f =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  h =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
END SCOPE
