SCOPE BEGIN
  a =>
    CONST BEGIN
      type:
        INTEGER
      value:
        5
    END CONST
  b =>
    CONST BEGIN
      type:
        INTEGER
      value:
        5
    END CONST
  c =>
    CONST BEGIN
      type:
        INTEGER
      value:
        5
    END CONST
  c2 =>
    CONST BEGIN
      type:
        INTEGER
      value:
        5
    END CONST
  d =>
    CONST BEGIN
      type:
        INTEGER
      value:
        5
    END CONST
  e =>
    CONST BEGIN
      type:
        INTEGER
      value:
        5
    END CONST
  f =>
    CONST BEGIN
      type:
        INTEGER
      value:
        5
    END CONST
  g =>
    CONST BEGIN
      type:
        INTEGER
      value:
        5
    END CONST
END SCOPE
