SCOPE BEGIN
  a =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  a2 =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  b =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  c =>
    INTEGER
  d =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  e =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  f =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  g =>
    INTEGER
  h =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  i =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  j =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  k =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  l =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  m =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  n =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  o =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  p =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
  q =>
    VAR BEGIN
      type:
        INTEGER
    END VAR
END SCOPE
